### ISSUE TITLE
Build failing on fresh install with starter kit

### ISSUE THREAD

**Issue by graphicgeek** [poetic/ember-cli-cordova#171] opened 2015-10-02 18:39 UTC
The ember build gives me this error:

Build failed.
ENOENT, no such file or directory 'pathtoproject/tmp/concat_with_maps-input_base_path-r0Usy0UC.tmp/0/bower_components/hammerjs/hammer.js'

I'm on iOS Yosemite (10.10.5) and have:
cordova: 5.0.0
ember: 1.13.8
node: 0.12.7
npm: 2.13.4

**Comment by graphicgeek** [comment] 2015-10-02 20:12
I don't know why this error would be happening on a fresh install, but I was able to fix it by going into the project directory and running:

bower install hammerjs

**Comment by BryanH** [comment] 2016-01-21 17:50
Gonna close this because it is old. If it is still happening, please open a new issue and include steps to recreate.

**Comment by tsm91** [comment] 2016-02-05 17:33
@graphicgeek @BryanH yes, this still exists

the problem is when you run `ember generate cordova-starter-kit` it doesn't run `bower install hammerjs --save`

**Comment by rjbain** [comment] 2016-03-03 18:29
@tsm91 Thank you! That fixed the problem for me.

**Comment by AlexBlom** [comment] 2016-03-10 02:11
Closing this. Please open again if you are having challenges.

**Closed by AlexBlom** 2016-03-10 02:11 UTC

**Comment by charliemitchell** [comment] 2016-09-10 01:53
I am having the same issue, I had to bower install hammerjs, then rename it to `hammer.js` because bower was installing it as `bower_components/hammerjs` and broccoli is looking for `bower_components/hammer.js/`. This was also a fresh install. If you guys won't fix, maybe make a note of it in the README, I vote for the fix though...

**Comment by BryanH** [comment] 2016-09-12 18:17
@charliemitchell Please submit a pull request and we'll merge it in

**Comment by runspired** [comment] 2016-09-13 01:22
@BryanH @charliemitchell this is an incorrect fix, but also you know there's now ember-cordova :D

**Comment by runspired** [comment] 2016-09-13 01:24
To be more clear, the reason this is an incorrect fix is that the starter kit is locked to old versions of ember-gestures et all, and hammer.js not hammerjs should have been installed by bower. There was an unfortunate hang up where both are now available on bower.

**Comment by charliemitchell** [comment] 2016-09-13 04:52
Yes, I opted for ember-cordova. Yes, that's unfortunate, but it happens. Ultimately, my comment above may help others who run into the same problem, if you guys want to add a note to the README, cool, I'll leave it up to you as I'm moving on to ember-cordova.
