### ISSUE TITLE
Android Platform :cannot connect to localhost:4200

### ISSUE THREAD

**Issue by kithokit** [poetic/ember-cli-cordova#105] opened 2014-12-13 15:41 UTC
Hi after building the android platform on ember-cli-cordova
When I `ember server` up running the app, the android simulator shows error message 
cannot connect to localhost:4200

Have u ever meet this issue as well?

**Comment by adamesque** [comment] 2015-08-04 21:38
FYI this doesn't appear to work currently, at least not with Android 5.1 — if I enable LiveReload, as soon as the app boots on the device, I get dumped out to Chrome, which tries to load the `emberUrl` URL in my config.

**Comment by AlexBlom** [comment] 2016-03-10 02:17
I think this is a duplicate of #105. Please open again if that is not the case.

**Closed by AlexBlom** 2016-03-10 02:17 UTC
